services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME}-nginx
    restart: unless-stopped
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
      CONTAINER_NAME: ${CONTAINER_NAME}
    volumes:
      - ./dist:/var/www/html/dist
      - ./.git:/var/www/html/.git
      - ./nginx/templates:/etc/nginx/templates:rw,cached
    networks:
      - proxy
      - default
    depends_on:
      - php
  php:
#   image: php:8-fpm
    build: ./Build/php/.
    container_name: ${CONTAINER_NAME}-php
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dist:/var/www/html/dist
      - ./.git:/var/www/html/.git
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
networks:
  proxy:
    external: true
  default: {}