services:
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.rlp-sms-beta-http.entrypoints=http"
      - "traefik.http.routers.rlp-sms-beta-http.rule=Host(`beta.rlp-sms.de`)"
      - "traefik.http.routers.rlp-sms-beta.entrypoints=https"
      - "traefik.http.routers.rlp-sms-beta.rule=Host(`beta.rlp-sms.de`)"
      - "traefik.http.routers.rlp-sms-beta.middlewares=default@file"
      - "traefik.http.routers.rlp-sms-beta.tls=true"
      - "traefik.http.routers.rlp-sms-beta.tls.certresolver=http"
      - "traefik.http.routers.rlp-sms-beta.service=rlp-sms-beta"
      - "traefik.http.services.rlp-sms-beta.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
  php:
    image: php:8-fpm
networks:
  proxy:
    external: true